import pytest

from mission10_uwb_protocol import Envelope, FrameError, decode_frame


# Generated by the Rust encoder from the OTP values read on the bench board.
GOLDEN_OTP = bytes.fromhex(
    "10 02 78 56 34 12 01 61 61 61 61 f0 3f f0 3f 19 "
    "02 be 04 01 02 01 05 93 c6 b3 fb 00"
)


def test_decodes_rust_golden_otp_frame():
    assert decode_frame(GOLDEN_OTP) == Envelope(
        protocol_version=2,
        sequence=0x12345678,
        kind="otp",
        fields=(0x61616161, 0x3FF03FF0, 0x00BE0019, 0x00010201),
    )


def test_rejects_corrupt_and_truncated_frames():
    corrupt = bytearray(GOLDEN_OTP)
    corrupt[4] ^= 0x40
    with pytest.raises(FrameError, match="CRC"):
        decode_frame(bytes(corrupt))
    with pytest.raises(FrameError, match="truncated"):
        decode_frame(GOLDEN_OTP[:-1])
