[package]
name = "mission10-uwb-protocol"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
test = true

[dependencies]
corncobs = "0.1.4"
crc = { version = "3.4.0", default-features = false }
hubpack = "0.1.2"
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
